---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
a = read.csv("Atrasados.csv", sep=",", encoding="UTF-8", header = TRUE, strip.white=TRUE)
a$Previsão.de.Entrega <- paste0("01/",a$Previsão.de.Entrega)
a$Previsão.de.Entrega <- as.Date(a$Previsão.de.Entrega,"%d/%m/%Y")
# a$Previsão.de.Entrega.Tabela <- strftime(a$Previsão.de.Entrega, "%b/%Y")
a$Previsão.de.Entrega.Tabela <- a$Previsão.de.Entrega

library(lubridate)
a$Previsão.de.Entrega <- a$Previsão.de.Entrega %m+% months(1)
a$Previsão.de.Entrega <- a$Previsão.de.Entrega - days(1)



a$Última.Comunicação <- as.Date(a$Última.Comunicação,"%d/%m/%Y")


a$Atraso <- as.numeric(difftime(Sys.Date(),a$Previsão.de.Entrega))
# a$Atraso <- as.numeric(a$Atraso)


# b <- ymd(a$Última.Comunicação)


a$Dif <- ifelse(difftime(Sys.Date(),a$Última.Comunicação)>120,"Sim","Não")



a <- a[,c(1,2,3,4,6,7,5,8)]

library(reactable)
library(htmlwidgets)




reactable(a, compact=TRUE, filterable=FALSE, searchable = TRUE, defaultPageSize = 30,defaultSortOrder="desc",defaultSorted="Atraso",
          language = reactableLang(
            noData = "Nenhum registro encontrado",
            searchPlaceholder = "Pesquisar",
            pageInfo = "{rowStart}\u2013{rowEnd} de {rows} registros",
            pageNext = "Próximo",
            pagePrevious = "Anterior"
          ),
          columns = list(
            Nome = colDef (cell = function(value, index){
              url <- a$Link[index]
              htmltools::tags$a(href = url, target = "_blank", as.character(value))
            }),
            Link = colDef(show=FALSE),
            Autor = colDef(align = "center"),
            Previsão.de.Entrega.Tabela = colDef(
              name = "Previsão de Entrega",
              align = "center",
              cell = function(value) {
                strftime(value, "%b/%Y")}),
            Atraso = colDef(name = "Atraso<br>(dias)",
                            align = "center",
                            cell = JS("function(cellInfo) {
                                      var today = new Date();
                                      var dd = String(today.getDate()).padStart(2, '0');
                                      var mm = String(today.getMonth() + 1).padStart(2, '0'); //January is 0!
                                      var yyyy = today.getFullYear();
                                      today = yyyy + '-' + mm + '-' + dd;
      
                                      var date1 = new Date(today)
                                      var date2 = new Date(cellInfo.row['Previsão.de.Entrega'])
      
                                      var diff = date1 - date2;
                                      var dias = Math.floor(diff/86400000)
      
                                      return '<b>' + dias + '</b>'
                                      }"
                                      ),html = TRUE),
          Última.Comunicação = colDef(
            name = "Última Comunicação",
            align = "center",
            cell = function(value) {
              strftime(value, "%d/%m/%Y")}),
          Previsão.de.Entrega = colDef(
            show = FALSE
          ),
          Dif = colDef(
            name = "Sem Comunicação?<br>(+ 120 dias)",
            align = "center",
            html = TRUE)
          
))
```

